
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Graphics;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Jan 9, 2013, 5:45:44 PM
 */
/**
 *
 * @author gurjar
 */
public class NewJFrame extends javax.swing.JFrame {
Connection conn=null;
   ResultSet rs=null;
   PreparedStatement pst=null;
   JTable info_table1;
   String name;
    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        //conn=javaconnect.ConnecrDb();
        conn=javaconnect.ConnecrDb();
       // Fillcombo();
        Update_table();
    }
public void Update_table(){
  //timer.start();
taxi_info ti=new taxi_info();
info_table1=ti.info_table;
    try{
    String sql ="select * from cabtable1  ";
   pst=conn.prepareStatement(sql);
   rs=pst.executeQuery();
   info_table1.setModel(DbUtils.resultSetToTableModel(rs));
 
 
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
 
 
    }



}
//private void Fillcombo(){
// 
// 
//try{
//    Update_table();
//  String sql="select * from cabtable1";
//  pst=conn.prepareStatement(sql);
//   rs=pst.executeQuery();
// //Update_table();
//   while(rs.next()){
//   String boarding =rs.getString("boarding");
//   ComboBox_name1.addItem(boarding);
//   ComboBox_name2.addItem(boarding);
// 
//   }
//
//}catch(Exception e){
//
//JOptionPane.showMessageDialog(null, e);
//
//} finally {
//try{
//  rs.close();
//      pst.close();
//    // conn.close();
//  }
//  catch(Exception e) {
//                   }
//      }
//
//
//
//
//
//}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new Draline();
        Draw = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ComboBox_name1 = new javax.swing.JComboBox();
        ComboBox_name2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(51, 255, 204));
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        Draw.setText("draw");
        Draw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DrawMouseClicked(evt);
            }
        });
        Draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrawActionPerformed(evt);
            }
        });

        jLabel1.setText("From");

        ComboBox_name1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ComboBox_name2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("To");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(Draw))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboBox_name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(Draw)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
class Draline extends JPanel{
    public void painComponent(Graphics g){
   // Graphics g = panel.getGraphics();
     g.drawLine(100, 150, 200, 500);
       
    }
}
    
    private void panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseClicked
        // TODO add your handling code here:
       
//        Graphics gg = panel.getGraphics();
//        paintComponent(gg);
        int x,y;
        JLabel label;
         x = evt.getX();
             y = evt.getY();
          label= new JLabel();
       //   String name="xk";
//         ImageIcon img=new ImageIcon("rail.jpeg");
//       label.setIcon(img);
 name = JOptionPane.showInputDialog("Enter the name of land mark");
          //label.setToolTipText(name);
          //label.getToolTipText(e);
    // label.sett
 ComboBox_name1.addItem(name);
 ComboBox_name2.addItem(name);
try{
String sql ="Insert into cabtable1 (Id,boarding,destination,seater,seattype,username,password,availability,allstationX,allstationY) values (?,?,?,?,?,?,?,?,?,?)";
 Random rand =new Random();
int rand1= rand.nextInt(1000);
         pst=conn.prepareStatement(sql);                
         
        pst.setString(1,Integer.toString(rand1) );
        pst.setString(2,name );
        pst.setString(3,Integer.toString(y) );
         pst.setString(4,"3 SEATER" );
         pst.setString(5,"AC" );
         pst.setString(6,"");
          pst.setString(7,"");
           pst.setString(8,"Available");
            pst.setString(9,Integer.toString(x));
             pst.setString(10,Integer.toString(y));
         
         
         pst.execute();
}        
    
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }
        Update_table(); 
        try{
String sql ="Insert into cabtable1 (Id,boarding,destination,seater,seattype,username,password,availability,allstationX,allstationY) values (?,?,?,?,?,?,?,?,?,?)";
 Random rand =new Random();
int rand1= rand.nextInt(1000);
         pst=conn.prepareStatement(sql);                
         
        
          pst.setString(1,Integer.toString(rand1) );
        pst.setString(2,name );
        pst.setString(3,Integer.toString(y) );
         pst.setString(4,"4 SEATER" );
         pst.setString(5,"NON-AC" );
         pst.setString(6,"");
          pst.setString(7,"");
           pst.setString(8,"Available");
            pst.setString(9,Integer.toString(x));
             pst.setString(10,Integer.toString(y));
         
         
         pst.execute();
}        
    
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }
        Update_table();
      if(name.equals("bus stand")){
          ImageIcon img=new ImageIcon("bus.2.jpg");
          label.setIcon(img);
       }
      else if(name.equals("railway station"))
      {
      ImageIcon img=new ImageIcon("rail.jpeg");
          label.setIcon(img);
     
     
      }
      else if(name.equals("hostel"))
      {
      ImageIcon img=new ImageIcon("hostel1.jpg");
          label.setIcon(img);
     
     
      }
      else
      {
      ImageIcon img=new ImageIcon("other.jpg");
          label.setIcon(img);
     
     
      }
          label.setLayout(new BorderLayout(
                  ));
        panel.add(label);
    
     label.setBounds(x,y,150,50);
     label.setToolTipText(name);
        
        
        
        
        
        
    }//GEN-LAST:event_panelMouseClicked

    private void DrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawMouseClicked
        // TODO add your handling code here:
        int x1=0,y1=0,x2=10,y2=10;
         Update_table();
        String tmp1 =(String)ComboBox_name1.getSelectedItem();            
            String sql1="select * from cabtable1 where boarding=?";
           try{
            pst=conn.prepareStatement(sql1);
            pst.setString(1, tmp1);
            rs=pst.executeQuery();
            if(rs.next()){
            String X1 =rs.getString("allstationX");
            x1=Integer.parseInt(X1);
            String Y1 =rs.getString("allstationY");
            y1=Integer.parseInt(Y1);
            }
            }
    
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }
     
    String tmp2 =(String)ComboBox_name2.getSelectedItem();            
            String sql2="select * from cabtable1 where boarding=?";
           try{
            pst=conn.prepareStatement(sql2);
            pst.setString(1, tmp2);
            rs=pst.executeQuery();
            if(rs.next()){
            String X2 =rs.getString("allstationX");
            x2=Integer.parseInt(X2);
            String Y2 =rs.getString("allstationY");
            y2=Integer.parseInt(Y2);
            }
            }
    
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }       
        Graphics g = panel.getGraphics();
        
        g.drawLine(x1+25, y1+25, x2+25, y2+25);
        
    }//GEN-LAST:event_DrawMouseClicked

    private void DrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrawActionPerformed

    }//GEN-LAST:event_DrawActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBox_name1;
    private javax.swing.JComboBox ComboBox_name2;
    private javax.swing.JButton Draw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
